version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    networks:
      - mynetwork
  duckdb:
    image: duckdb/duckdb
    volumes:
      - ./data:/data  # Mount the directory with the JSON file
    command: ["duckdb", "/data/data.json"]  # Example command for querying JSON
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
